on: workflow_dispatch

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install -Dmaven.test.skip=true -U
      - name: Depcheck
        uses: MatthewSwanick-Idexx/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --disableOssIndex false
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
